# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/umbrella-sampling',
                'doc_host': 'https://pablo-unzueta.github.io',
                'git_url': 'https://github.com/pablo-unzueta/umbrella-sampling',
                'lib_path': 'umbrella_sampling'},
  'syms': {'umbrella_sampling.core': {'umbrella_sampling.core.foo': ('core.html#foo', 'umbrella_sampling/core.py')}}}
