# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_umbrella.ipynb.

# %% auto 0
__all__ = ['compute_cv', 'biased_potential']

# %% ../nbs/00_umbrella.ipynb 3
def compute_cv(config):
    # Compute the value of the CV given a system configuration
    return cv_value

def biased_potential(cv_value, target_value, force_constant):
    # Compute the value of the harmonic biasing potential
    return 0.5 * force_constant * (cv_value - target_value)**2
